spring.application.name=bff-agendador

# URLs dos microserviços (COM http:// e COM o path completo)
usuario.url=http://localhost:8080/usuario
tarefas.url=http://localhost:8081/tarefas
notificacao.url=http://localhost:8082/email

# Porta do BFF
server.port=8083

# Logs do Feign para debug
logging.level.com.projetozero=DEBUG
logging.level.com.projetozero.bffagendador.infra.client=DEBUG
feign.client.config.default.loggerLevel=full

cron.horario=0/30 0/1 * * * ?

usuario.email=feljava32@gmail.com
usuario.senha=123456

spring.cloud.openfeign.okhttp.enabled=true